# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# clone directory
clone_folder: c:\projects\osre

# branches to build
branches:
  # whitelist
  only:
    - master

image:
  - Visual Studio 2017
  - Visual Studio 2019
    
platform:
  #- x86
  - x64
  
configuration: Release

init:
- if "%platform%" EQU "x64" ( for %%a in (2008 2010 MinGW) do ( if "%Configuration%"=="%%a" (echo "Skipping unsupported configuration" && exit /b 1 ) ) )

install:
# Make compiler command line tools available
- ps: Start-FileDownload 'https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip'
- ps: 7z x SDL2-devel-2.0.5-VC.zip
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" set CMAKE_GENERATOR_NAME=Visual Studio 16 2019
- if "%platform%"=="x64" set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_NAME% Win64
- call scripts/appveyor/setup_repo.bat
- cmake %CMAKE_DEFINES% -G "%CMAKE_GENERATOR_NAME%"

before_build:
- call c:\projects\osre\scripts\appveyor\setup_repo.bat

build:
  parallel: true
  project: osre.sln

after_build:
  - 7z a osre.7z c:\projects\osre\bin\release\* c:\projects\osre\lib\release\*

artifacts:
  - path: osre.7z
    name: osre_lib
